---
- name: Copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Start app
  shell: |
    npm install
    sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
    pm2 stop default
    pm2 start npm -- start
    pm2 save
