---
- name: Copy artifact
  copy:
    src: artifact.tar.gz
    dest: ~/artifact.tar.gz

- name: Extract artifact
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: Start app
  shell: |
    cd backend
    npm install
    pm2 stop default
    pm2 start npm -- start
