version: 2.1

commands:
  install-dependencies:
    description: Install project dependencies
    parameters:
      project-name:
        description: Project name
        type: string
    steps:
      - checkout
      - restore_cache:
          keys: [<< parameters.project-name >>-build]
      - run:
          name: Install Dependencies
          command: |
            cd << parameters.project-name >>
            npm ci
  
  test-project:
    description: Run project unit tests
    parameters:
      project-name:
        description: Project name
        type: string
    steps:
      - run:
          name: Test project
          command: |
            cd << parameters.project-name >>
            npm run test
  
  scan-project:
    description: Scan project dependencies for vulnerabilities
    parameters:
      project-name:
        description: Project name
        type: string
    steps:
      - run:
          name: Test project
          command: |
            cd << parameters.project-name >>
            npm audit --audit-level=critical

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: frontend
      - run:
          name: Build front-end
          command: |
            cd frontend
            npm run build:prod
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build-backend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: backend
      - run:
          name: Build back-end
          command: |
            cd backend
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build
  test-frontend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: frontend
      - test-project:
          project-name: frontend
  test-backend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: backend
      - test-project:
          project-name: backend
            
  scan-frontend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: frontend
      - scan-project:
          project-name: frontend

  scan-backend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: backend
      - scan-project:
          project-name: backend

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      - test-frontend:
          requires: [build-frontend]
      - test-backend:
          requires: [build-backend]
      - scan-frontend:
          requires: [build-frontend]
      - scan-backend:
          requires: [build-backend]