version: 2.1

commands:
  install-dependencies:
    description: Install project dependencies
    parameters:
      project-name:
        description: Project name
        type: string
    steps:
      - checkout
      - restore_cache:
          keys: [<< parameters.project-name >>-build]
      - run:
          name: Install Dependencies
          command: |
            cd << parameters.project-name >>
            npm ci

jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: frontend
      - run:
          name: Build front-end
          command: |
            npm run lint
            npm run test:cov
            npm run build:prod
      - save_cache:
          paths: [frontend/node_modules]
          key: frontend-build
  build-backend:
    docker:
      - image: circleci/node:13.14.0
    steps:
      - install-dependencies:
          project-name: backend
      - run:
          name: Build back-end
          command: |
            npm run lint
            npm run test:cov
            npm run build
      - save_cache:
          paths: [backend/node_modules]
          key: backend-build

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend